// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/code.go
//
// Generated by this command:
//
//	mockgen -source=./internal/service/code.go -package=svcmocks -destination=./internal/service/mocks/code.mock.go
//

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCodeServicer is a mock of CodeServicer interface.
type MockCodeServicer struct {
	ctrl     *gomock.Controller
	recorder *MockCodeServicerMockRecorder
	isgomock struct{}
}

// MockCodeServicerMockRecorder is the mock recorder for MockCodeServicer.
type MockCodeServicerMockRecorder struct {
	mock *MockCodeServicer
}

// NewMockCodeServicer creates a new mock instance.
func NewMockCodeServicer(ctrl *gomock.Controller) *MockCodeServicer {
	mock := &MockCodeServicer{ctrl: ctrl}
	mock.recorder = &MockCodeServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodeServicer) EXPECT() *MockCodeServicerMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockCodeServicer) Send(ctx context.Context, biz, phone string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, biz, phone)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockCodeServicerMockRecorder) Send(ctx, biz, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockCodeServicer)(nil).Send), ctx, biz, phone)
}

// Verify mocks base method.
func (m *MockCodeServicer) Verify(ctx context.Context, biz, phone, inputCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, biz, phone, inputCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockCodeServicerMockRecorder) Verify(ctx, biz, phone, inputCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockCodeServicer)(nil).Verify), ctx, biz, phone, inputCode)
}
